#!/bin/bash
#
# Sets up python environment. The user should create
# a .pythonrc file to handle common imports when entering python IDE

sourcedir=$(readlink -e $(dirname -- $BASH_SOURCE))

# Python IDE convenience
export PYTHONSTARTUP=$sourcedir/.pythonrc

# Access dataenvy modules
export PYTHONPATH="$sourcedir/modules:$PYTHONPATH"
