#!/bin/bash
#
# Submission script for many python scripts shared in each dataset

sourcefn=$BASH_SOURCE
errorsig="ERROR: $sourcefn"
sourcedir=$(readlink -e $(dirname -- $sourcefn))

workingdir=$PWD

datapaths=($DATAPATHS)

args=$@

for datapath in "${datapaths[@]}"; do

    cd $datapath

    source local.sh

    if [[ $args == *".toml"* ]]; then
	modules=($MODULES)
	for module in "${modules[@]}"; do
	    cd $module
	    submit-script $args
	    cd -
	done
    else
	$args
    fi

    cd $workingdir
	
done
